server:
  port: 8080
spring:
  datasource:
    url: "jdbc:mysql://$PROJECT_NAME-db/$DB_NAME"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: "$DB_USER"
    password: "$DB_PASSWORD"

  jpa:
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL8Dialect"
        ddl-auto: "create"
