server:
  port: 8080
spring:
  datasource:
    url: "jdbc:mysql://localhost:17134/intergationTesting?useUnicode=true&characterEncoding=utf-8"
    username: "intergationTesting"
    password: "yunzhi.club"

  jpa:
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL57Dialect"
        hibernate:
          ddl-auto: "create"
