server:
  port: 8080
spring:
  datasource:
    url: "jdbc:mysql://location:17134/intergationTesting?useUnicode=true&characterEncoding=utf-8"
    username: "intergationTesting"
    password: "yunzhi.club"

  jpa:
    hibernate:
      ddl-auto: update
