server:
  port: 8080
spring:
  application:
    name: dentistry
  datasource:
    url: "jdbc:mysql://$PROJECT_NAME-db/$DB_NAME?useUnicode=true&characterEncoding=utf-8"
    username: "$DB_USER"
    password: "$DB_PASSWORD"

  jpa:
    hibernate:
      ddl-auto: update
