server:
  port: 8080

spring:
  datasource:
     url: "jdbc:mysql://localhost:3312/integrationTesting?characterEncoding=utf-8"
     username: "root"
     password: "yunzhi"
  jpa:
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL57Dialect"
        hibernate:
          ddl-auto: "create"

logging:
  level:
    club:
      yunzhi: info
    root: info
