server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://localhost:3312/integrationTesting?characterEncoding=utf-8"
    username: "root"
    password: "yunzhi"
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL57Dialect"
        hibernate:
          ddl-auto: "create-drop"