server:
  port: 8080

spring:
  datasource:
    #    提交机器人测试，数据库
   url: "jdbc:mysql://mysql/integrationTesting?characterEncoding=utf-8"
   username: "root"
   password: "root"
#    生成环境下
    # url: "jdbc:mysql://localhost:3312/dentistry?characterEncoding=utf-8"
    # username: "root"
    # password: "yunzhi"
  jpa:
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL57Dialect"
        hibernate:
          ddl-auto: "create"

logging:
  level:
    club:
      yunzhi: info
    root: info
