server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/integrationTesting"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: "root"
    password: "yunzhi"
  jpa:
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL8Dialect"
        ddl-auto: "create"

logging:
  level:
    club:
      yunzhi: info
    root: info
